[package]
name = "vexcore"
version = "0.1.0"
edition = "2024"

[dependencies]
# Internal
vexmacro.workspace = true
# External
paste.workspace = true
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
proc-macro-crate = "3.4.0"